"use client";
import dynamic from "next/dynamic";
import { useCallback, useEffect, useState } from "react";
import { CakeSlice, ChevronDown, HelpCircle, Maximize, Users, X } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import AvatarPreview from "@/components/avatar-preview";
const OfficeScene = dynamic(() => import("@/components/office-scene"), { ssr: false });
const birthdays = [{ name:"Ana",date:"05 de outubro",color:"#f6a0a9",initial:"A" },{ name:"Bruno",date:"12 de outubro",color:"#9cb7f6",initial:"B" },{ name:"Carla",date:"28 de outubro",color:"#f0756e",initial:"C" }];
type ChatMessage={id:number;name:string;text:string};
export default function Home(){
 const [birthdayOpen,setBirthdayOpen]=useState(false),[creatorOpen,setCreatorOpen]=useState(false),[controlsOpen,setControlsOpen]=useState(false),[chatOpen,setChatOpen]=useState(false);const [name,setName]=useState("Você"),[avatar,setAvatar]=useState("r"),[created,setCreated]=useState(false),[action,setAction]=useState<"idle"|"dance"|"wave">("idle"),[chatText,setChatText]=useState(""),[messages,setMessages]=useState<ChatMessage[]>([]),[bubble,setBubble]=useState("");
 useEffect(()=>{const id=window.setTimeout(()=>{const raw=localStorage.getItem("dtec-personagem"),history=localStorage.getItem("dtec-chat");if(history)try{setMessages(JSON.parse(history).slice(-5))}catch{}if(!raw)return;try{const s=JSON.parse(raw);setName(s.name);setAvatar(s.avatar);setCreated(true)}catch{}},0);return()=>clearTimeout(id)},[]);
 const save=()=>{const clean=name.trim().slice(0,18)||"Colega DTEC";setName(clean);setCreated(true);setCreatorOpen(false);localStorage.setItem("dtec-personagem",JSON.stringify({name:clean,avatar}))};
 const avatarClick=useCallback(()=>setControlsOpen(true),[]),birthdayClick=useCallback(()=>setBirthdayOpen(true),[]);
 const sendMessage=(e:React.FormEvent)=>{e.preventDefault();const text=chatText.trim().slice(0,100);if(!text)return;const next=[...messages,{id:Date.now(),name,text}].slice(-5);setMessages(next);setBubble(text);setChatText("");setAction("wave");localStorage.setItem("dtec-chat",JSON.stringify(next));window.setTimeout(()=>{setBubble("");setAction("idle")},5000)};
 return <main className="app-shell"><OfficeScene name={name} avatar={avatar} action={action} message={bubble} created={created} remoteUsers={[]} onStateChange={()=>{}} onAvatarClick={avatarClick} onBirthdayClick={birthdayClick}/><div className="shade"/>
 <header className="topbar"><div className="brand">DTEC</div><span className="divider"/><div className="online"><Users size={23}/><b>•</b><span>8 na sala</span></div><div className="top-actions"><button aria-label="Tela cheia" onClick={()=>document.documentElement.requestFullscreen?.()}><Maximize/></button><button aria-label="Ajuda" onClick={()=>setControlsOpen(true)}><HelpCircle/></button><button className={`profile ${created?"":"google-entry"}`} aria-label={created?"Abrir perfil":"Entrar com Google"} onClick={()=>setCreatorOpen(true)}><span>{created?name.slice(0,2).toUpperCase():"G"}</span>{created&&<ChevronDown size={17}/>}</button></div></header>
 {created&&<nav className="actionbar" aria-label="Ações do personagem"><button onClick={()=>setAction(action==="dance"?"idle":"dance")}>{action==="dance"?"Parar":"Dançar"}</button><button onClick={()=>setChatOpen(v=>!v)}>Conversar</button><button onClick={()=>setCreatorOpen(true)}>Meu avatar</button></nav>}
 {chatOpen&&<form className="chat-pop" onSubmit={sendMessage}><strong>Conversar</strong><input autoFocus value={chatText} onChange={e=>setChatText(e.target.value)} placeholder="Digite uma mensagem..." maxLength={100}/><button>Enviar</button></form>}
 {messages.length>0&&<aside className="chat-history" aria-label="Últimas mensagens"><h3>Conversas recentes</h3>{messages.map(m=><p key={m.id}><strong>{m.name}</strong><span>{m.text}</span></p>)}</aside>}
 {controlsOpen&&<div className="avatar-pop"><button className="close-mini" onClick={()=>setControlsOpen(false)}><X/></button><strong>{name}</strong><small>Você assumiu o controle.</small><p>Clique no chão para caminhar.</p><button onClick={()=>setAction(action==="dance"?"idle":"dance")}>Dançar</button><button onClick={()=>setCreatorOpen(true)}>Editar personagem</button></div>}
 <Dialog open={creatorOpen} onOpenChange={setCreatorOpen}><DialogContent className="creator-dialog" overlayClassName="creator-overlay"><DialogHeader><DialogTitle>Escolha seu personagem</DialogTitle><DialogDescription>O escritório continua ativo enquanto você escolhe.</DialogDescription></DialogHeader><label>Seu nome<input value={name==="Você"?"":name} onChange={e=>setName(e.target.value)} placeholder="Digite seu nome" maxLength={18}/></label><div className="avatar-grid">{["a","c","f","j","n","r"].map((id,i)=><button key={id} aria-label={`Personagem ${i+1}`} className={avatar===id?"selected":""} onClick={()=>setAvatar(id)}><AvatarPreview model={id}/><b>{i+1}</b></button>)}</div><button className="primary" onClick={save}>Entrar na sala</button></DialogContent></Dialog>
 <Dialog open={birthdayOpen} onOpenChange={setBirthdayOpen}><DialogContent className="birthday-dialog"><DialogHeader><div className="birthday-title"><CakeSlice/><DialogTitle>Aniversariantes<br/><em>de Outubro</em></DialogTitle></div><DialogDescription>Vamos celebrar quem faz aniversário neste mês.</DialogDescription></DialogHeader><div className="birthday-list">{birthdays.map(i=><article key={i.name}><span style={{background:i.color}}>{i.initial}</span><div><strong>{i.name}</strong><p>{i.date}</p></div></article>)}</div><footer>Parabéns a todos!<small>Que seja um novo ciclo incrível! ♥</small></footer></DialogContent></Dialog></main>}
