"use client";
import dynamic from "next/dynamic";
import { useCallback, useEffect, useRef, useState } from "react";
import { CakeSlice, ChevronDown, HelpCircle, Maximize, MessageCircle, Sparkles, UserRound, Users, X } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
const OfficeScene = dynamic(() => import("@/components/office-scene"), { ssr: false });
const birthdays = [{ name:"Ana",date:"05 de outubro",color:"#f6a0a9",initial:"A" },{ name:"Bruno",date:"12 de outubro",color:"#9cb7f6",initial:"B" },{ name:"Carla",date:"28 de outubro",color:"#f0756e",initial:"C" }];
type ChatMessage={id:number;name:string;text:string};
type RemoteUser={userId:string;name:string;avatar:string;x:number;z:number;action:string;message:string;lastSeen:number};
export default function Home(){
 const [birthdayOpen,setBirthdayOpen]=useState(false),[creatorOpen,setCreatorOpen]=useState(false),[controlsOpen,setControlsOpen]=useState(false),[chatOpen,setChatOpen]=useState(false);const [name,setName]=useState("Você"),[avatar,setAvatar]=useState("r"),[created,setCreated]=useState(false),[action,setAction]=useState<"idle"|"dance"|"wave">("idle"),[chatText,setChatText]=useState(""),[messages,setMessages]=useState<ChatMessage[]>([]),[bubble,setBubble]=useState(""),[remoteUsers,setRemoteUsers]=useState<RemoteUser[]>([]),[connected,setConnected]=useState(false);const lastState=useRef(0);
 useEffect(()=>{const raw=localStorage.getItem("dtec-personagem"),history=localStorage.getItem("dtec-chat");if(history)try{setMessages(JSON.parse(history).slice(-5))}catch{}if(!raw){setCreatorOpen(true);return}try{const s=JSON.parse(raw);setName(s.name);setAvatar(s.avatar);setCreated(true)}catch{setCreatorOpen(true)}},[]);
 useEffect(()=>{let active=true;const sync=async()=>{try{const res=await fetch("/api/room",{cache:"no-store"});if(!res.ok)return;const data=await res.json();if(!active)return;setConnected(true);setRemoteUsers(data.online??[]);setMessages((data.messages??[]).slice(-5));if(data.profile&&!created){setName(data.profile.name);setAvatar(data.profile.avatar);setCreated(true);setCreatorOpen(false);localStorage.setItem("dtec-personagem",JSON.stringify({name:data.profile.name,avatar:data.profile.avatar}))}}catch{setConnected(false)}};sync();const id=window.setInterval(sync,2000);return()=>{active=false;clearInterval(id)}},[created]);
 const save=async()=>{const clean=name.trim().slice(0,18)||"Colega DTEC";setName(clean);setCreated(true);setCreatorOpen(false);localStorage.setItem("dtec-personagem",JSON.stringify({name:clean,avatar}));try{await fetch("/api/room",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"profile",name:clean,avatar})});setConnected(true)}catch{}};
 const avatarClick=useCallback(()=>setControlsOpen(true),[]),birthdayClick=useCallback(()=>setBirthdayOpen(true),[]);
 const sendMessage=async(e:React.FormEvent)=>{e.preventDefault();const text=chatText.trim().slice(0,100);if(!text)return;const next=[...messages,{id:Date.now(),name,text}].slice(-5);setMessages(next);setBubble(text);setChatText("");setAction("wave");localStorage.setItem("dtec-chat",JSON.stringify(next));try{await fetch("/api/room",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"message",name,text})})}catch{}window.setTimeout(()=>{setBubble("");setAction("idle")},5000)};
 const publishState=useCallback((x:number,z:number,currentAction:string)=>{const now=Date.now();if(now-lastState.current<900)return;lastState.current=now;fetch("/api/room",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"state",x,z,action:currentAction,message:bubble})}).catch(()=>setConnected(false))},[bubble]);
 return <main className="app-shell"><OfficeScene name={name} avatar={avatar} action={action} message={bubble} created={created} remoteUsers={remoteUsers} onStateChange={publishState} onAvatarClick={avatarClick} onBirthdayClick={birthdayClick}/><div className="shade"/>
 <header className="topbar"><div className="brand">DTEC</div><span className="divider"/><div className="online"><Users size={23}/><b className={connected?"":"offline"}>•</b><span>{remoteUsers.length+1} online</span></div><div className="top-actions"><button aria-label="Tela cheia" onClick={()=>document.documentElement.requestFullscreen?.()}><Maximize/></button><button aria-label="Ajuda" onClick={()=>setControlsOpen(true)}><HelpCircle/></button><button className="profile" onClick={()=>setCreatorOpen(true)}><span>{name.slice(0,2).toUpperCase()}</span><ChevronDown size={17}/></button></div></header>
 {!created&&<button className="create-character" onClick={()=>setCreatorOpen(true)}><UserRound/> Criar personagem</button>}
 <nav className="actionbar" aria-label="Ações do personagem"><button className="dance" onClick={()=>setAction(action==="dance"?"idle":"dance")}><Sparkles/> {action==="dance"?"Parar":"Dançar"}</button><button className="talk" onClick={()=>setChatOpen(v=>!v)}><MessageCircle/> Conversar</button><button onClick={()=>setCreatorOpen(true)}><UserRound/> Meu avatar</button></nav>
 {chatOpen&&<form className="chat-pop" onSubmit={sendMessage}><strong>Conversar</strong><input autoFocus value={chatText} onChange={e=>setChatText(e.target.value)} placeholder="Digite uma mensagem..." maxLength={100}/><button>Enviar</button></form>}
 {messages.length>0&&<aside className="chat-history" aria-label="Últimas mensagens"><h3>Conversas recentes</h3>{messages.map(m=><p key={m.id}><strong>{m.name}</strong><span>{m.text}</span></p>)}</aside>}
 {controlsOpen&&<div className="avatar-pop"><button className="close-mini" onClick={()=>setControlsOpen(false)}><X/></button><strong>{name}</strong><small>Você assumiu o controle.</small><p>Clique no chão para caminhar.</p><button onClick={()=>setAction(action==="dance"?"idle":"dance")}>Dançar</button><button onClick={()=>setCreatorOpen(true)}>Editar personagem</button></div>}
 <Dialog open={creatorOpen} onOpenChange={setCreatorOpen}><DialogContent className="creator-dialog"><DialogHeader><DialogTitle>Crie seu personagem</DialogTitle><DialogDescription>Escolha como seus colegas verão você no escritório.</DialogDescription></DialogHeader><label>Seu nome<input value={name==="Você"?"":name} onChange={e=>setName(e.target.value)} placeholder="Digite seu nome" maxLength={18}/></label><div className="avatar-grid">{["a","c","f","j","n","r"].map((id,i)=><button key={id} className={avatar===id?"selected":""} onClick={()=>setAvatar(id)}><span className={`avatar-dot avatar-${id}`}>●</span><b>{["Azul","Violeta","Coral","Verde","Dourado","DTEC"][i]}</b></button>)}</div><button className="primary" onClick={save}>Entrar na sala</button></DialogContent></Dialog>
 <Dialog open={birthdayOpen} onOpenChange={setBirthdayOpen}><DialogContent className="birthday-dialog"><DialogHeader><div className="birthday-title"><CakeSlice/><DialogTitle>Aniversariantes<br/><em>de Outubro</em></DialogTitle></div><DialogDescription>Vamos celebrar quem faz aniversário neste mês.</DialogDescription></DialogHeader><div className="birthday-list">{birthdays.map(i=><article key={i.name}><span style={{background:i.color}}>{i.initial}</span><div><strong>{i.name}</strong><p>{i.date}</p></div></article>)}</div><footer>Parabéns a todos!<small>Que seja um novo ciclo incrível! ♥</small></footer></DialogContent></Dialog></main>}
