"use client";
import {useEffect,useRef} from "react";import * as THREE from "three";import{GLTFLoader}from"three/examples/jsm/loaders/GLTFLoader.js";import{clone}from"three/examples/jsm/utils/SkeletonUtils.js";
type Props={name:string;avatar:string;action:"idle"|"dance"|"wave";message:string;created:boolean;onAvatarClick:()=>void;onBirthdayClick:()=>void};
const people=[
 {n:"Helio Vianey Carreiro Veloso Filho",m:"a",x:-6,z:2},
 {n:"Herbert Alves Marinho",m:"c",x:-1,z:-1},
 {n:"Edvar Gusmão Florencio",m:"f",x:4,z:0},
 {n:"Otoniel Angelo Pereira Galvão",m:"j",x:-6,z:7},
 {n:"Tiago Salomão",m:"n",x:2,z:7},
 {n:"Gabriel Cavalcante de Lima Oliveira",m:"r",x:8,z:7},
 {n:"Bruno Leão Dias",m:"a",x:8,z:2},
];
function card(text:string,bubble=false){const c=document.createElement("canvas");c.width=bubble?700:512;c.height=bubble?180:128;const x=c.getContext("2d")!;x.fillStyle=bubble?"white":"#1b2945";x.roundRect(7,7,c.width-14,c.height-(bubble?38:14),bubble?38:34);x.fill();x.fillStyle=bubble?"#17264a":"white";x.font=`${bubble?600:700} ${bubble?42:45}px Arial`;x.textAlign="center";x.textBaseline="middle";x.fillText(text,c.width/2,bubble?78:64,c.width-70);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));s.scale.set(bubble?4.5:2.6,bubble?1.15:.65,1);return s}
export default function OfficeScene({name,avatar,action,message,created,onAvatarClick,onBirthdayClick}:Props){const host=useRef<HTMLDivElement>(null);useEffect(()=>{if(!host.current)return;const el=host.current,scene=new THREE.Scene();scene.background=new THREE.Color(0xbcc7d3);const camera=new THREE.OrthographicCamera(-15,15,9,-9,.1,100);camera.position.set(18,21,22);camera.lookAt(0,0,2);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setSize(el.clientWidth,el.clientHeight);el.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xfff8e8,0x66758b,2.7));const sun=new THREE.DirectionalLight(0xfff2d7,4.8);sun.position.set(-10,22,15);sun.castShadow=true;scene.add(sun);
 const mat=(c:number)=>new THREE.MeshStandardMaterial({color:c,roughness:.72}),box=(w:number,h:number,d:number,c:number,x:number,y:number,z:number)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;scene.add(o);return o},chairs:THREE.Mesh[]=[];box(28,.5,19,0xead7b8,0,-.25,2);box(28,4,.45,0xf4efe6,0,2,-7.4);box(.45,4,19,0xf1ece5,-13.8,2,2);box(5,1.2,2.1,0x8f9ba9,-9,.6,-3.8);box(1.2,.55,1.2,0xb9824d,-8,.28,-.8);box(4.7,.08,3.2,0x315b8b,-9,.06,-1.3);
 [[0,1.5],[0,5.5],[-8,7.5],[8,-3.7]].forEach(([x,z])=>{box(6,.35,1.8,0xc68a46,x,.85,z);for(const sx of[-2,0,2]){box(1.2,.75,.12,0x263341,x+sx,1.55,z);const ch=box(.75,.72,.75,0x30353c,x+sx,.36,z+1.45);ch.userData.seat={x:x+sx,z:z+1.45};chairs.push(ch)}});box(6,.38,2.6,0xb97c3d,7,.85,-4);for(const x of[4.7,6.2,7.8,9.3]){const ch=box(.8,.95,.8,0x25344a,x,.45,-2.4);ch.userData.seat={x,z:-2.4};chairs.push(ch)}box(3.2,2.2,.8,0xa87540,7,1.1,0);for(let i=0;i<11;i++){const p=box(.48,.42,.48,0xe4ded3,-12+i*2.25,.22,-6.8),g=new THREE.Mesh(new THREE.SphereGeometry(.48,7,6),mat(0x3f863a));g.scale.y=1.4;g.position.set(p.position.x,.9,p.position.z);scene.add(g)}
 const board=box(5.2,2.3,.18,0xf3a51f,2.2,2.5,-7.05),panel=box(4.8,1.9,.08,0xfffbf1,2.2,2.5,-6.93),bl=card("🎈 ANIVERSARIANTES 🎂");bl.position.set(2.2,2.5,-6.82);bl.scale.set(4.2,1,1);scene.add(bl);const sign=card("DTEC");sign.position.set(-10,2.7,-6.9);sign.scale.set(4,1.15,1);scene.add(sign);
 const loader=new GLTFLoader(),mixers:THREE.AnimationMixer[]=[];let mine:THREE.Object3D|null=null,mineMixer:THREE.AnimationMixer|null=null,current:THREE.AnimationAction|null=null,auto=true,seating=false,target=new THREE.Vector3(0,0,5),clips=new Map<string,THREE.AnimationClip>();const add=(model:string,n:string,x:number,z:number,self=false)=>loader.load(`/models/kenney/character-${model}.glb`,g=>{const o=clone(g.scene);o.scale.setScalar(.85);o.position.set(x,0,z);o.traverse(v=>{if((v as THREE.Mesh).isMesh)(v as THREE.Mesh).castShadow=true});const l=card(n);l.position.y=2.65;o.add(l);if(self&&message){const b=card(message,true);b.position.y=3.65;o.add(b)}scene.add(o);const mx=new THREE.AnimationMixer(o);mixers.push(mx);const map=new Map(g.animations.map(c=>[c.name.toLowerCase(),c]));const walk=map.get("walk")||map.get("idle");if(walk)mx.clipAction(walk).play();if(self){mine=o;mineMixer=mx;clips=map}});people.forEach(p=>add(p.m,p.n,p.x,p.z));add(avatar,created?name:"Você",0,5,true);
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),floor=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3();const click=(e:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height*2-1));ray.setFromCamera(pointer,camera);if(mine&&ray.intersectObject(mine,true).length){auto=false;onAvatarClick();return}if(ray.intersectObjects([board,panel],false).length){onBirthdayClick();return}const seat=ray.intersectObjects(chairs,false)[0];if(seat){auto=false;seating=true;const p=seat.object.userData.seat;target.set(p.x,0,p.z);return}if(ray.ray.intersectPlane(floor,hit)){auto=false;seating=false;target.set(THREE.MathUtils.clamp(hit.x,-12.5,12.5),0,THREE.MathUtils.clamp(hit.z,-6,10))}};renderer.domElement.addEventListener("pointerup",click);
 let mode="",frameId=0;const play=(key:string)=>{if(mode===key||!mineMixer)return;current?.fadeOut(.12);const clip=clips.get(key)||clips.get("idle");if(clip){current=mineMixer.clipAction(clip);current.reset().fadeIn(.12).play()}mode=key},clock=new THREE.Clock(),frame=()=>{frameId=requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.04);mixers.forEach(m=>m.update(dt));if(mine&&mineMixer){if(action==="dance")play("emote-yes");else if(action==="wave")play("interact-right");else{if(auto&&mine.position.distanceTo(target)<.35)target.set(THREE.MathUtils.randFloat(-11,11),0,THREE.MathUtils.randFloat(-5.5,9));const d=target.clone().sub(mine.position);if(d.length()>.18){play("walk");d.normalize();mine.position.addScaledVector(d,dt*(auto?1.15:2.4));mine.rotation.y=Math.atan2(d.x,d.z)}else play(seating?"sit":"idle")}}renderer.render(scene,camera)};frame();const resize=()=>{const a=el.clientWidth/el.clientHeight,fr=12;camera.left=-fr*a;camera.right=fr*a;camera.top=fr;camera.bottom=-fr;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)};resize();window.addEventListener("resize",resize);return()=>{cancelAnimationFrame(frameId);window.removeEventListener("resize",resize);renderer.domElement.removeEventListener("pointerup",click);renderer.dispose();el.replaceChildren()}},[avatar,created,name,onAvatarClick,onBirthdayClick,action,message]);return <div ref={host} className="office-canvas"/>}
